package com.example.smartBiz.dto;

import lombok.*;

@AllArgsConstructor
@NoArgsConstructor
@Data
public class ProductsDto {
    private Long id;
    private String name;
    private Double price;

    // ✅ NEW (auto generated by backend)
    private String sku;

    // ✅ NEW
    private Long categoryId;
    private String categoryName;

    // ✅ show calculated stock (sum of batches)
    private Integer availableStock;

    private Integer lowStockLimit;
    private Long supplierId;
}
